### PR TITLE
ParameterizedLogging recipe fixed

### LINKED ISSUE #159: ParameterizedLogging recipe doesn't support Log4j2 Marker
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v5.34.0
- Maven/Gradle plugin v3.9.8
- rewrite-logging-frameworks v2.9.1

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml

            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>5.34.0</version>
                <configuration>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.logging.log4j.ParameterizedLogging</recipe>
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-logging-frameworks</artifactId>
                        <version>2.9.1</version>
                    </dependency>
                </dependencies>
            </plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
@Log4j2
class A {
    public static final Marker                             MY_MARKER                     = MarkerManager.getMarker("my-A");
    void foo(String bar) {
       log.debug(MY_MARKER, "foo1");
       log.debug(MY_MARKER, "foo2 " + bar);
        log.debug(MY_MARKER, () -> bar);
    }
}
```

## What did you expect to see?

```java
@Log4j2
class A {
    public static final Marker                             MY_MARKER                     = MarkerManager.getMarker("my-A");
    void foo(String bar) {
       log.debug(MY_MARKER, "foo1");
       log.debug(MY_MARKER, "foo2 {}", bar);
        log.debug(MY_MARKER, () -> bar);
    }
}
```

## What did you see instead?

```java
@Log4j2
class A {
    public static final Marker                             MY_MARKER                     = MarkerManager.getMarker("my-A");
    void foo(String bar) {
       log.debug(“{}”, MY_MARKER, "foo1");
       log.debug("{}", MY_MARKER, "foo2 " + bar);
        log.debug("{}", MY_MARKER, () -> bar);
    }
}
```

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```

### PR DESCRIPTION
**Pull request by Riyazul555**
## Any additional context
- Fixes #159 

### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [ ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by Riyazul555** [comment]
@timtebeek please check this PR
thanks

**Comment by timtebeek** [comment]
Thanks for getting this started @Riyazul555 ; I've added a unit test to highlight what I think should happen here, based on what @jeffreye had described in #159 . Would you want to fix those arguments still?

**Comment by Riyazul555** [comment]
No thanks @timtebeek 
You can just draft it

**Comment by jeffreye** [comment]
Thank you both. I just looked at the PR, we should also consider log4j2 and other markers( if any) as well.

Best,
Jeffrey
________________________________

**Comment by Riyazul555** [comment]
@timtebeek can you provide me more what do you need in this PR ?
Thanks

**Comment by timtebeek** [comment]
Sure; if you run the new test I added you'll find it produces an unexpected result
```diff
Unexpected result in "Test.java":
    diff --git a/Test.java b/Test.java
    index d494749..01aece4 100644
    --- a/Test.java
    +++ b/Test.java
    @@ -3,6 +3,6 @@ 
 
     class Test {
         static void method(Logger logger, Marker marker, String name) {
    -        logger.info(marker, "Hello {}, nice to meet you {}", name, name);
    +        logger.info("Hello {}, nice to meet you {}", marker, name, name);
         }
     }
```
You'll notice that the marker is moved from being the first argument, to being the second, which changes the behavior. We'll want to keep the marker as the first argument.

**Comment by timtebeek** [comment]
Superseeded by 
- #162

**Pull request closed without merging**
