### PR TITLE
ParameterizedLogging recipe fixed

### LINKED ISSUE #159: ParameterizedLogging recipe doesn't support Log4j2 Marker
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v5.34.0
- Maven/Gradle plugin v3.9.8
- rewrite-logging-frameworks v2.9.1

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml

            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>5.34.0</version>
                <configuration>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.logging.log4j.ParameterizedLogging</recipe>
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-logging-frameworks</artifactId>
                        <version>2.9.1</version>
                    </dependency>
                </dependencies>
            </plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
@Log4j2
class A {
    public static final Marker                             MY_MARKER                     = MarkerManager.getMarker("my-A");
    void foo(String bar) {
       log.debug(MY_MARKER, "foo1");
       log.debug(MY_MARKER, "foo2 " + bar);
        log.debug(MY_MARKER, () -> bar);
    }
}
```

## What did you expect to see?

```java
@Log4j2
class A {
    public static final Marker                             MY_MARKER                     = MarkerManager.getMarker("my-A");
    void foo(String bar) {
       log.debug(MY_MARKER, "foo1");
       log.debug(MY_MARKER, "foo2 {}", bar);
        log.debug(MY_MARKER, () -> bar);
    }
}
```

## What did you see instead?

```java
@Log4j2
class A {
    public static final Marker                             MY_MARKER                     = MarkerManager.getMarker("my-A");
    void foo(String bar) {
       log.debug(“{}”, MY_MARKER, "foo1");
       log.debug("{}", MY_MARKER, "foo2 " + bar);
        log.debug("{}", MY_MARKER, () -> bar);
    }
}
```

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```

### PR DESCRIPTION
**Pull request by Riyazul555**
## What's changed?
Explanation of Changes:
Argument Handling:

A check is added to detect if the Marker argument is present.
If a Marker is detected, it ensures that it remains as the first argument.
Argument Reordering:

After constructing the new argument list, if a Marker is detected, it is added at the beginning of the newArgList.
Test Adjustments:

Ensure that your tests verify that the Marker argument remains in the correct position and that the logging message is parameterized correctly.

## Any additional context
- Fixes #159 

### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [ ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by Riyazul555** [comment]
@timtebeek please checkout this PR
Do tell me if any changes  are required
Thanks

**Comment by Riyazul555** [comment]
Any update on this PR @timtebeek ??

**Comment by timtebeek** [comment]
I had a quick look already, but I'm out today. The class does not yet compile, and the test fails when I fix compilation. That'll need work still

**Comment by Riyazul555** [comment]
Ok thanks @timtebeek 
I guess there was some error with parenthesis of the test code 
That's why compilation error I guess 
Nevertheless

**Review by timtebeek — APPROVED** [review]
Thanks again for getting this started; I've pushed up the remaining changes to get it going.

**Comment by Riyazul555** [comment]
Thanks @timtebeek

**Pull request merged**
